version: "3.8"

services:
  app:
    image: node
    container_name: reservationsweb
    restart: on-failure:3
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=YeiiMaccDev123
      - DATABASE_NAME=barbershop_db
    volumes:
      - .:/app
    reservations:
      - db
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
  db:
    image: mysql
    container_name: barbershop_db
    ports:
      - "3307:3306"
    # logging:
    #   driver: none
    environment:
      - MYSQL_DATABASE=barbershop_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=YeiiMaccDev123
      - MYSQL_ROOT_PASSWORD=YeiiMaccDev123
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
